const assert=require('node:assert/strict');const T=require('../app/src/main/assets/engine.js');let count=0;function test(n,f){f();console.log('PASS',n);count++}function advance(s,n){s.speed=4;for(let i=0;i<n/4;i++)T.tick(s,1)}
test('Senawang opening campaign and MYR capital',()=>{let s=T.fresh();assert.equal(s.cash,500);assert.equal(s.level,1);assert.deepEqual(Object.keys(s.locations),['senawang']);assert.equal(s.riders.length,0)});
test('Production consumes physical stock and costs stay with inventory',()=>{let s=T.fresh();T.startBatch(s,'honeydew',20);assert.equal(s.stock.powder,600);assert.equal(s.stock.milk,1500);assert.equal(s.stock.bottles,20);assert.equal(s.cash,500);assert.equal(s.daily.cogs,0);advance(s,28);assert.equal(T.ready(s),20);assert.equal(s.production,null);assert.equal(T.unitCost(s,'honeydew'),1.38)});
test('Oversized batch and insufficient cash rejected without mutation',()=>{let s=T.fresh(),before=JSON.stringify(s);assert.throws(()=>T.startBatch(s,'honeydew',100));assert.equal(JSON.stringify(s),before);assert.throws(()=>T.purchase(s,'powder',100000,'premium'));assert.equal(JSON.stringify(s),before)});
test('Weighted purchasing, supplier delay and no double profit expense',()=>{let s=T.fresh();T.purchase(s,'powder',1000,'budget');assert.equal(s.stock.powder,1000);assert.equal(s.orders.length,1);assert.equal(s.daily.expenses,0);T.nextDay(s);assert.equal(s.stock.powder,2000);assert.ok(Math.abs(s.unitCosts.powder-.03115)<1e-9);assert.equal(s.orders.length,0)});
test('Rider allocation, commission and unsold return reconcile',()=>{let s=T.fresh();s.level=2;T.hireRider(s);T.startBatch(s,'coffee',20);advance(s,28);let cash=s.cash;T.dispatch(s,s.riders[0].id,'senawang','coffee',10);assert.equal(T.ready(s),10);assert.throws(()=>T.dispatch(s,s.riders[0].id,'senawang','coffee',1));advance(s,60);assert.equal(s.routes.length,0);assert.equal(s.riders[0].busy,false);assert.equal(T.ready(s)+s.sold,20);assert.equal(s.daily.expenses,s.sold);assert.equal(s.cash,cash+s.sold*6)});
test('Paused time changes nothing',()=>{let s=T.fresh(),before=JSON.stringify(s);T.tick(s,1);assert.equal(JSON.stringify(s),before)});
test('Price elasticity affects demand',()=>{let a=T.fresh(),b=T.fresh();for(let s of[a,b]){s.batches=[{id:1,flavour:'honeydew',qty:100,cost:1.38,recipe:{sweet:2,strong:2},expires:3}];s.open=true}satisfy=undefined;T.setPrice(b,'senawang',15);advance(a,240);advance(b,240);assert.ok(a.sold>b.sold)});
test('Spoilage expense is recognized only once',()=>{let s=T.fresh();s.batches=[{id:1,flavour:'coffee',qty:10,cost:1.5,recipe:{sweet:2,strong:2},expires:1}];T.nextDay(s);assert.equal(T.ready(s),0);assert.equal(s.profit,-15);T.nextDay(s);assert.equal(s.profit,-15)});
test('Bulk contract pays once and uses only requested flavour',()=>{let s=T.fresh();s.level=3;T.contract(s);let c=s.contract;s.batches=[{id:1,flavour:c.flavour,qty:c.qty,cost:1.5,recipe:{sweet:2,strong:2},expires:3}];T.fulfil(s);assert.equal(s.daily.revenue,c.qty*6.5);assert.equal(T.ready(s),0);assert.throws(()=>T.fulfil(s))});
test('Partner split cannot repeatedly distribute retained profit',()=>{let s=T.fresh();s.cash=2000;s.profit=1000;T.distribute(s);assert.equal(s.withdrawals.Wan,200);assert.equal(s.withdrawals.Husein,200);assert.equal(s.cash,1600);assert.throws(()=>T.distribute(s));s.profit=1100;T.distribute(s);assert.equal(s.withdrawals.Wan,220)});
test('Seven chapters and six districts are reachable, campaign wins',()=>{let s=T.fresh();s.cash=100000;s.sold=2500;s.rep=90;for(let i=1;i<7;i++)T.upgrade(s);for(let z of T.ZONES)if(z.id!=='senawang')T.openBranch(s,z.id);for(let i=0;i<7;i++){s.daily.revenue=1000;T.nextDay(s)}assert.equal(s.level,7);assert.equal(Object.keys(s.locations).length,6);assert.equal(s.won,true)});
test('Save roundtrip, invalid save and malicious avatar rejection',()=>{let s=T.fresh();s.speed=4;let restored=T.validate(JSON.parse(JSON.stringify(s)));assert.equal(restored.speed,0);assert.equal(restored.cash,500);assert.throws(()=>T.validate({version:2}));s.avatar='data:image/jpeg;base64," onerror="alert(1)';assert.throws(()=>T.validate(s))});
console.log(count+' engine tests passed');
