const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs');const http=require('http');const path=require('path');
(async()=>{let server=http.createServer((req,res)=>{let f=path.join(__dirname,'../app/src/main/assets',req.url==='/'?'index.html':req.url);try{res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.jpg')?'image/jpeg':f.endsWith('.mp3')?'audio/mpeg':f.endsWith('.m4a')?'audio/mp4':'text/html');res.end(fs.readFileSync(f))}catch(e){res.statusCode=404;res.end()}});await new Promise(r=>server.listen(8777,'127.0.0.1',r));let b;try{b=await chromium.launch({headless:true});let p=await b.newPage({viewport:{width:960,height:540}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8777');await p.getByRole('heading',{name:'Your empire starts at home.'}).waitFor();fs.mkdirSync('qa',{recursive:true});await p.screenshot({path:'qa/01-welcome.png'});await p.locator('#playerName').fill('Wan');await p.locator('#difficulty').selectOption('easy');await p.locator('#startCash').fill('1000');await p.getByRole('button',{name:"Let's build something"}).click();await p.evaluate(()=>UI.close());await p.waitForTimeout(400);await p.screenshot({path:'qa/02-senawang-home.png'});
async function point(sel){let r=await p.locator(sel).first().boundingBox();assert.ok(r,sel);return{x:r.x+r.width/2,y:r.y+r.height/2}}async function dragTo(from,to){let a=await point(from),b=await point(to);await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(b.x,b.y,{steps:12});await p.mouse.up();}
await p.getByRole('button',{name:'Open counter',exact:true}).click();await p.waitForFunction(()=>UI.state().counter.queue.length>0);let flavour=await p.evaluate(()=>Service.order(UI.state()).flavour);await p.getByRole('button',{name:'Pause & close',exact:true}).click();let frozen=await p.evaluate(()=>UI.state().time);
await dragTo('[data-drag="cup"]','#cupZone');assert.equal(await p.evaluate(()=>UI.state().counter.cup.container),'cups');
for(let i=0;i<5;i++){let a=await point('[data-drag="spoon"]'),b=await point('[data-flavour="'+flavour+'"]'),c=await point('#cupZone');await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(b.x,b.y,{steps:8});await p.mouse.move(c.x,c.y,{steps:8});await p.mouse.up()}
assert.equal(await p.evaluate(()=>UI.state().counter.cup.powder),20);
for(let [k,target] of [['milk',25],['water',200]]){let a=await point('[data-drag="'+k+'"]'),b=await point('#cupZone');await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(b.x,b.y,{steps:8});await p.waitForFunction(([k,t])=>UI.state().counter.cup[k]>=t-1,[k,target]);await p.mouse.up()}
await dragTo('[data-drag="ice"]','#cupZone');let a=await point('[data-drag="stir"]'),c=await point('#cupZone');await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(c.x,c.y,{steps:8});for(let i=0;i<40;i++)await p.mouse.move(c.x+20*Math.cos(i*.4),c.y+20*Math.sin(i*.4));await p.mouse.up();assert.equal(await p.evaluate(()=>UI.state().counter.cup.mixed),true);await dragTo('[data-drag="lid"]','#cupZone');await dragTo('#drink','#readyShelf');assert.equal(await p.evaluate(()=>UI.state().counter.shelf.length),1);assert.equal(await p.evaluate(()=>UI.state().time),frozen);await p.reload();await p.waitForFunction(()=>typeof UI!=='undefined'&&UI.state());assert.equal(await p.evaluate(()=>UI.state().counter.shelf.length),1);await p.getByRole('button',{name:'Open counter',exact:true}).click();await dragTo('[data-drag="stored"]','[data-order]');assert.equal(await p.evaluate(()=>UI.state().counter.served),1);assert.equal(await p.evaluate(()=>UI.state().counter.xp),50);assert.equal(await p.evaluate(()=>UI.state().counter.shelf.length),0);await p.getByRole('button',{name:'Pause & close',exact:true}).click();await p.screenshot({path:'qa/07-counter-service.png'});
await p.evaluate(()=>UI.panel('Kitchen'));await p.locator('#batchQty').fill('20');await p.getByRole('button',{name:'Start mixing'}).click();assert.equal(await p.evaluate(()=>UI.state().production.qty),20);await p.evaluate(()=>{UI.speed(4);for(let i=0;i<8;i++)Tycoon.tick(UI.state(),1);UI.speed(0);UI.panel('Kitchen')});assert.equal(await p.evaluate(()=>Tycoon.ready(UI.state())),20);await p.screenshot({path:'qa/03-kitchen.png'});
await p.evaluate(()=>{UI.speed(0);let s=UI.state();s.sold=0;UI.panel('Growth')});await p.getByRole('button',{name:'Grow the business'}).click();assert.equal(await p.evaluate(()=>UI.state().level),1);assert.match(await p.locator('#toast').innerText(),/Need 20 lifetime sales/);
await p.evaluate(()=>{let s=UI.state();s.sold=20;s.rep=20;s.cash=179;UI.panel('Growth')});await p.getByRole('button',{name:'Grow the business'}).click();assert.equal(await p.evaluate(()=>UI.state().level),1);
await p.evaluate(()=>{UI.state().cash=500;UI.panel('Growth')});await p.getByRole('button',{name:'Grow the business'}).click();assert.equal(await p.evaluate(()=>UI.state().level),2);assert.equal(await p.evaluate(()=>UI.state().cash),320);assert.match(await p.locator('#toast').innerText(),/New business chapter unlocked/);await p.reload();await p.waitForFunction(()=>typeof UI!=='undefined'&&UI.state());assert.equal(await p.evaluate(()=>UI.state().level),2);
await p.evaluate(()=>{Tycoon.hireRider(UI.state());UI.panel('Riders')});await p.getByRole('button',{name:'Send out to sell'}).click();assert.equal(await p.evaluate(()=>UI.state().routes.length),1);await p.evaluate(()=>{UI.speed(4);for(let i=0;i<16;i++)Tycoon.tick(UI.state(),1);UI.speed(0);UI.panel('Inbox')});assert.ok(await p.getByText(/Back from Senawang:/).count());await p.screenshot({path:'qa/04-rider-inbox.png'});
await p.evaluate(()=>{let c=document.createElement('canvas');c.width=300;c.height=300;let ctx=c.getContext('2d');ctx.fillStyle='#f1c46b';ctx.fillRect(0,0,300,300);ctx.fillStyle='#265b48';ctx.fillRect(80,80,140,140);UI.receiveAvatar(c.toDataURL('image/png'))});await p.locator('#cropCanvas').waitFor();await p.locator('#cropZoom').fill('1.5');await p.getByRole('button',{name:'Use this photo'}).click();assert.ok(await p.evaluate(()=>UI.state().avatar.startsWith('data:image/jpeg;base64,')));await p.evaluate(()=>UI.musicVolume(30));await p.evaluate(()=>UI.toggleMusic());assert.equal(await p.evaluate(()=>UI.state().musicEnabled),false);await p.reload();await p.waitForFunction(()=>typeof UI!=='undefined'&&UI.state());assert.equal(await p.evaluate(()=>UI.state().level),2);assert.equal(await p.evaluate(()=>UI.state().musicVolume),30);assert.equal(await p.evaluate(()=>UI.state().musicEnabled),false);assert.ok(await p.evaluate(()=>UI.state().avatar.length>100));
for(let name of ['Supplies','Growth','Team','Ledger','Today','Guide','Founder']){await p.evaluate(n=>UI.panel(n),name);assert.ok(await p.locator('#panelBody').innerText())}
await p.evaluate(()=>{let s=UI.state();s.cash=100000;s.sold=3000;s.rep=90;while(s.level<7)Tycoon.upgrade(s);for(let z of Tycoon.ZONES)if(!s.locations[z.id])Tycoon.openBranch(s,z.id);UI.close();MapView.overview()});await p.waitForTimeout(300);await p.screenshot({path:'qa/05-seremban-empire.png'});
await p.setViewportSize({width:800,height:360});await p.waitForTimeout(300);await p.screenshot({path:'qa/06-small-android.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);for(let sel of ['#readyShelf','#cupZone','.shelf-row>button:last-child']){let r=await p.locator(sel).boundingBox();assert.ok(r.y+r.height<=303,sel+' clipped by navigation')}assert.deepEqual(errors,[]);console.log('PASS browser: first-run tutorial, production, rider sales, inbox, avatar crop, persistence, all panels, empire map, small landscape layout.');}finally{if(b)await b.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
