const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs');const http=require('http');const path=require('path');
(async()=>{let server=http.createServer((req,res)=>{let f=path.join(__dirname,'../app/src/main/assets',req.url==='/'?'index.html':req.url);try{res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.jpg')?'image/jpeg':f.endsWith('.mp3')?'audio/mpeg':f.endsWith('.m4a')?'audio/mp4':'text/html');res.end(fs.readFileSync(f))}catch(e){res.statusCode=404;res.end()}});await new Promise(r=>server.listen(8777,'127.0.0.1',r));let b;try{b=await chromium.launch({headless:true});let p=await b.newPage({viewport:{width:960,height:540}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8777');await p.getByRole('heading',{name:'Your empire starts at home.'}).waitFor();fs.mkdirSync('qa',{recursive:true});await p.screenshot({path:'qa/01-welcome.png'});await p.locator('#playerName').fill('Wan');await p.locator('#difficulty').selectOption('easy');await p.locator('#startCash').fill('1000');await p.getByRole('button',{name:"Let's build something"}).click();await p.evaluate(()=>UI.close());await p.waitForTimeout(400);await p.screenshot({path:'qa/02-senawang-home.png'});
await p.getByRole('button',{name:'Open counter',exact:true}).click();await p.waitForFunction(()=>UI.state().counter.queue.length>0);await p.getByRole('button',{name:'Take cup',exact:true}).click();await p.locator('#drinkFlavour').selectOption(await p.evaluate(()=>Service.order(UI.state()).flavour));let powder=p.locator('[data-pour="powder"]');await powder.hover();await p.mouse.down();await p.waitForTimeout(1600);await p.mouse.up();assert.ok(await p.evaluate(()=>UI.state().counter.cup.powder>10));await p.evaluate(()=>{let s=UI.state(),o=Service.order(s),c=s.counter.cup,t=Service.targets(o);for(let k of Object.keys(t)){let rate={powder:12,milk:16,water:110,ice:1}[k];while(c[k]<t[k]-.01)Service.pour(s,k,Math.min(.1,(t[k]-c[k])/rate))}});await p.getByRole('button',{name:'Mix drink',exact:true}).click();await p.getByRole('button',{name:'Put on lid',exact:true}).click();await p.getByRole('button',{name:'Serve selected',exact:true}).click();assert.equal(await p.evaluate(()=>UI.state().counter.served),1);await p.evaluate(()=>{UI.speed(0);UI.state().open=false});await p.screenshot({path:'qa/07-counter-service.png'});
await p.evaluate(()=>UI.panel('Kitchen'));await p.locator('#batchQty').fill('20');await p.getByRole('button',{name:'Start mixing'}).click();assert.equal(await p.evaluate(()=>UI.state().production.qty),20);await p.evaluate(()=>{UI.speed(4);for(let i=0;i<8;i++)Tycoon.tick(UI.state(),1);UI.speed(0);UI.panel('Kitchen')});assert.equal(await p.evaluate(()=>Tycoon.ready(UI.state())),20);await p.screenshot({path:'qa/03-kitchen.png'});
await p.evaluate(()=>{UI.speed(0);let s=UI.state();s.sold=0;UI.panel('Growth')});await p.getByRole('button',{name:'Grow the business'}).click();assert.equal(await p.evaluate(()=>UI.state().level),1);assert.match(await p.locator('#toast').innerText(),/Need 20 lifetime sales/);
await p.evaluate(()=>{let s=UI.state();s.sold=20;s.rep=20;s.cash=179;UI.panel('Growth')});await p.getByRole('button',{name:'Grow the business'}).click();assert.equal(await p.evaluate(()=>UI.state().level),1);
await p.evaluate(()=>{UI.state().cash=500;UI.panel('Growth')});await p.getByRole('button',{name:'Grow the business'}).click();assert.equal(await p.evaluate(()=>UI.state().level),2);assert.equal(await p.evaluate(()=>UI.state().cash),320);assert.match(await p.locator('#toast').innerText(),/New business chapter unlocked/);await p.reload();await p.waitForFunction(()=>typeof UI!=='undefined'&&UI.state());assert.equal(await p.evaluate(()=>UI.state().level),2);
await p.evaluate(()=>{Tycoon.hireRider(UI.state());UI.panel('Riders')});await p.getByRole('button',{name:'Send out to sell'}).click();assert.equal(await p.evaluate(()=>UI.state().routes.length),1);await p.evaluate(()=>{UI.speed(4);for(let i=0;i<16;i++)Tycoon.tick(UI.state(),1);UI.speed(0);UI.panel('Inbox')});assert.ok(await p.getByText(/Back from Senawang:/).count());await p.screenshot({path:'qa/04-rider-inbox.png'});
await p.evaluate(()=>{let c=document.createElement('canvas');c.width=300;c.height=300;let ctx=c.getContext('2d');ctx.fillStyle='#f1c46b';ctx.fillRect(0,0,300,300);ctx.fillStyle='#265b48';ctx.fillRect(80,80,140,140);UI.receiveAvatar(c.toDataURL('image/png'))});await p.locator('#cropCanvas').waitFor();await p.locator('#cropZoom').fill('1.5');await p.getByRole('button',{name:'Use this photo'}).click();assert.ok(await p.evaluate(()=>UI.state().avatar.startsWith('data:image/jpeg;base64,')));await p.evaluate(()=>UI.musicVolume(30));await p.evaluate(()=>UI.toggleMusic());assert.equal(await p.evaluate(()=>UI.state().musicEnabled),false);await p.reload();await p.waitForFunction(()=>typeof UI!=='undefined'&&UI.state());assert.equal(await p.evaluate(()=>UI.state().level),2);assert.equal(await p.evaluate(()=>UI.state().musicVolume),30);assert.equal(await p.evaluate(()=>UI.state().musicEnabled),false);assert.ok(await p.evaluate(()=>UI.state().avatar.length>100));
for(let name of ['Supplies','Growth','Team','Ledger','Today','Guide','Founder']){await p.evaluate(n=>UI.panel(n),name);assert.ok(await p.locator('#panelBody').innerText())}
await p.evaluate(()=>{let s=UI.state();s.cash=100000;s.sold=3000;s.rep=90;while(s.level<7)Tycoon.upgrade(s);for(let z of Tycoon.ZONES)if(!s.locations[z.id])Tycoon.openBranch(s,z.id);UI.close();MapView.overview()});await p.waitForTimeout(300);await p.screenshot({path:'qa/05-seremban-empire.png'});
await p.setViewportSize({width:800,height:360});await p.waitForTimeout(300);await p.screenshot({path:'qa/06-small-android.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);console.log('PASS browser: first-run tutorial, production, rider sales, inbox, avatar crop, persistence, all panels, empire map, small landscape layout.');}finally{if(b)await b.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
